#############################
##---> Database Config --->##
#############################

#For save data
mongodb:
  host: '127.0.0.1'
  port: 27017
  database: 'database'
  authentication:
    enabled: true
    user: 'root'
    password: 'password'
    database: 'database'
#For sync rank
redis:
  host: ''
  port: 16693
  password: ''

