name: Zoom
version: 1.5
main: club.frozed.core.Zoom
description: All-in-One Server Core developed on Frozed Club Development.
website: www.frozed.club
softdepend:
  - PlaceholderAPI
  - MVdWPlaceholderAPI
authors:
  - Ryzeon
  - Elb1to
