name: Zoom
version: 1.0-SNAPSHOT
main: club.frozed.core.Zoom
description: All-in-Core Server Core developed by Frozed Club Development
website: www.frozed.club
softdepend: [Vault]
authors:
  - Ryzeon
  - Elb1to
