# Bukkit Sounds List -> https://jd.bukkit.org/org/bukkit/Sound.html (If you don't want to have any sound, just put the sound as 'none'
SETTINGS:
  PREFIX: '&8[&6Zoom&8]'
  SERVER-NAME: 'DEV'
  VAULT-SUPPORT: true
  CHAT:
    NAME-COLOR-MENU-TITLE: '&eChoose your name color'
    CHATCOLOR-MENU-TITLE: '&eChoose your chat color'
    FORMAT:
      ENABLED: true
      DEFAULT-COLOR: YELLOW
      FORMAT: '<rank><tag><nameColor><name>&7: <chatcolor><text>'
    MUTE: false
    DELAY: 3
  STAFF-CHAT:
    FORMAT: '&7(&9SC&7)&7(&e<server>&7) &f<player>&7: &e<text>'
    SOUND: 'NOTE_PLING' #Only in toggle msg
    TOGGLE: '&eYou <status> &estaff-chat'
  ADMIN-CHAT:
    FORMAT: '&7(&cAC&7)&7(&e<server>&7) &f<player>&7: <text>'
    SOUND: 'NOTE_PLING' #Only in toggle msg
    TOGGLE: '&eYou <status> &eadmin-chat'
  TIPS:
    ENABLED: true
    DELAY: 60
    MODE: normal # Select a random number or announcer in order
    TIPS-LIST: #Use {0} if you want a separator line before the tip. {C}
      - '&6Hello World!'
      - '&6Zoom Core!'
      - '&6Test Tip'
  PRIVATE-MESSAGES:
    NOTIFICATION-SOUND: 'NOTE_PLING' # put none or NONE to disable sounds
    FORMAT: # <rank>,<prefix>
      SENDER: '&7(To &e<target>&7) -> &e<text>'
      TARGET: '&7(From &e<sender>&7) -> &e<text>'
      SOCIAL-SPY: '&7[&dSocial-Spy&7] &e<sender> &7-> &e<target> &7» <text>'
  REPORT:
    COOLDOWN: 60
    MSG:
      SENDER: '&eYou reported &f<target> &eabout <text>.'
      STAFF: '&7[&cReport&7] &7[<server>] &f<sender> &ereported &f<target> &eabout <reason>'
      COOLDOWN: '&eYou must be wait &e<time> &f<left> &eto report another player.'
  COMMANDS-BLOCKED:
    MSG: '&cThis command is blocked.'
    LIST:
      - '/plugins'
      - '/bukkit:pl'
      - '/pl'
  NAME-MC-CHECK:
    ENABLED: true
    SOUND: 'ORB_PICKUP'
    JOIN-MSG:
      - '&7&m----------------------------------------------------'
      - '&eVote for us in NameMC to get the &6Verified Prefix&e! &6https://namemc.com/server/frozed.club'
      - '&7&m----------------------------------------------------'
    SERVER-IP: 'frozed.club'
    EXECUTE-CMD: 'setperm <player> tag.verfied'